### ISSUE TITLE
llvm/clang 12 rc compiled kernel wont boot

### ISSUE THREAD

**Issue by ptr1337** [kevall474/Linux#1]
hey, 
i have compiled your new llvm12 rc package, after that i rebooted and started compiling the kernel with llvm/clang but it wont boot. 
also tested with compiling the linux tkg kernel with llvm, same issue. 

got an nvidia gpu. 

Maybe got a solution? 

Thanks for your nice work, im in love with the cacule scheduler.

**Comment by kevall474** [comment]
Hi,

Thanks for the feedback. Did you also recompile mesa package against llvm12 rc package? If not this can be an issue of not booting to the system. I'll try to compile the new 5.11.6 kernel tonight against llvm12 rc package. I'll let you know.

Thanks.

**Comment by ptr1337** [comment]
Nope, didnt compile the mesa package. i will do it now. 
when you updated the repo for 5.11.6 ill try again :)

**Comment by kevall474** [comment]
You can compile mesa with : 
my package : https://github.com/kevall474/Mesa
or
Lone_Wolf aur package : https://aur.archlinux.org/packages/mesa-git/

**Comment by ptr1337** [comment]
Do i need to set env _llvm=y _compiler=2 ? 

Not sure right now. Sorry for the stupid question :x

**Comment by kevall474** [comment]
Hi,

Sorry I did not add a README.md file yet. So there's no stupid question. But for you there's no point to pass _llvm=y because you have a nvidia gpu. The enable-llvm-by-default.patch will work just for AMD gpu's because on AMD card we can use ACO shader compiler by Valve or LLVM.

You can pass env _compiler=(1 or 2) makepkg -s

1 is for compiling with gcc 
2 is for compiling with clang

or simply run makepkg -s and it will compile with gcc by default. At your choice.

**Comment by ptr1337** [comment]
Alright, thank you! Compiled lib32-mesa-rc and mesa-rc.
Also used llvm-rc, think its more stable for my usage. 

Also tried your gcc-git package,  but i didnt read the pkgbuild and build it false, but its a trunk i know. :p 
Mostly it compiled successfully, but there was a issue at the end because  gcc is at version 11.0.1 and the PKGBUILD says 11.0. 
Maybe just a issue because i didn't compiled the other packages first. 

Really looking forward with your packages. Great improvements since i discovered your repo. (mostly one of the first :D)
Since using the cacule schedueler and your other patches kernel, my input lag with my controller seems mostly gone. Got this issue long long time (playing much rocket league and there is a was a big difference to normally on windows). 
Tried several tkg's kernel options and builds, also several proton-tkg builds, but never got the input lag problem solved. 

your build and/or the cacule scheduler solved the problem. really appreciate your work!


If you need some help, i got a server which ressources are mostly not used (4gb ram from 16gb used), i can host you a wiki/repo/mail whatever your needs. Just hit me up.

**Comment by kevall474** [comment]
Alright thanks!

I'm looking to create an achlinux unofficial repo for my pkg's. I'll hit you up when I'm ready. 

When I'll buy my pinebook I'll look to add support for arm/arm64 machine.

WIth covid here in Canada and the lock down it's a good time to work on archlinux stuff!

Thanks for the support.

**Comment by ptr1337** [comment]
I got a MacBook Air M1 (which is arm64 architecture), if compiling is possible with that, i can do it for you.
Also owned a ODROID HC4 and Raspberry Pi 4 and running Arch on it, there i can also compile fast with distccd. 
When your PKGBUILDS are adjusted to it, i can give it a try. 
Maybe think about a domainname, endings with for example: kevall.sh or kevall.dev are looking good. 

True, same for me. :p 

Regards.

**Comment by ptr1337** [comment]
Still same issue, maybe something needed because the nvidia drivers. 
using right now nvidia-tkg drivers. 

Later i will recompile llvm and create mesa directly after it. 
Should i use llvm git or rc? also with mesa. 

But a working gcc11 build would be also nice. But no hustle. 

regards.

**Comment by kevall474** [comment]
Hi,

When you build llvm/clang (git or rc package) do it in a tty env. Directly after building and installing build mesa-(stable,rc or git) lib32-mesa-(stable,rc or git). llvm/clang rc can be more stable llvm/clang git package. 
After building llvm/clang and mesa reboot your system and start compiling the kernel you want.

I have compile all 5.11.6 kernels from my repo against llvm/clang rc package and installed on my 2 laptops with no issues.

Here is the specs of my 2 machines :

1 AMD Ryzen 9 3900x CPU with AMD Rx580x GPU :

llvm/clang version -> 12.0.0rc3
mesa-rc lib32-mesa-rc -> 21.0.0-rc5
OS: Arch Linux x86_64
Kernel: 5.11.6-linux-kernel-muqss
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/580/58

2 HP laptop with Intel i5-1035G1 CPU and Intel Iris Plus Graphics G1 GPU :

llvm/clang verison -> llvm 13.0.0git
mesa-git lib32-mesa-git -> 21.1.0_devel
OS: Arch Linux x86_64
Kernel: 5.11.6-linux-kernel-cacule
CPU: Intel i5-1035G1 (8) @ 3.600GHz
GPU: Intel Iris Plus Graphics G1

Even my laptop running llvm/clang and mesa git package run on a linux kernel build with llvm/clang rc package. 

Just for trouble shouting have you tryied to boot your system with llvm/clang (rc or git package) with mesa-(stable, rc or git package) lib32-mesa-(stable, rc or git package) but with the official linux or linux-zen 5.11.6 version from the official arch repo?

Maybe recompile nvidia-tkg package against llvm/clang (rc or git package)? I have no nvidia GPU so I don't know very much about these packages.

And for the gcc-git package I suggest you to uninstall it and install the official gcc package by Archlinux. There is a glitch in compiling all the toolchain espacialy with binutils that breaks the toolchain (because of not providing /usr/bin/ld) It's been a while I have not working on this project.

Hope that can help you!

**Comment by kevall474** [comment]
Just for your information I have compile nvidia package from Archlinux and it builded the modules just for the official linux package 5.11.6. I t did not build for linux-zen, linux-kernel, linux-kernel-muqss, linux-kernel-bmq, linux-kernel-pds, linux-kernel-cacule and linux-kernel-ups. I don't know if this can help you. Maybe just copy the mudules like that :

- Compile nvidia package with makepkg -s

- cp pkg/usr/lib/modules/5.11.6-arch1-1/extramodules/* /usr/lib/modules/(linux-kernel;linux-kernel-muqss;linux-kernel-bmq;linux-kernel-pds;linux-kernel-cacule;linux-kernel-upds;5.11.6-zen1-1-zen)/extramodules/

Just an idea

**Comment by ptr1337** [comment]
Seems really weird. Maybe llvm dont like nvidia :p. 

Ive recompiled nvidia packages, and tried a a compile a kernel with gcc/llvm. but mear at the end it was broken. 

Trying again with llvm, if not. i have to wair for gcc11.

**Comment by ptr1337** [comment]
Mostly dkms is failing. I think its because the nvidia-tkg. their also writing if building wit a mostlyportablly gcc build to build the nvidia-tkg driver with it, if not it is failing. 

Ill create a issue their. maybe someone got a "bugfix"

**Comment by kevall474** [comment]
Yeah I think it's on nvidia stuff side. Because I'm running 5.11.6 kernel since yesterday! I do not have any systems with nvidia GPU so maybe on linux-tkg repo you can have help. If you can find what is the issues feel free to create a pull request to add it to the README.md file!
